version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_locked_investment
    environment:
      POSTGRES_DB: locked_investment_db
      POSTGRES_USER: investment
      POSTGRES_PASSWORD: 123

    ports:
      - "5432:5432"
    volumes:
      - locked_investment_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U investment"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  locked_investment_postgres_data: